
CondaError: Run 'conda init' before 'conda deactivate'

2024-11-13 12:54:26,259 - INFO - Starting the main function
2024-11-13 12:54:26,260 - INFO - Parameters loaded successfully.
2024-11-13 12:54:26,260 - ERROR - Failed to load gaze data from /gpfs/milgram/project/chang/pg496/data_dir/social_gaze/intermediates/nan_removed_gaze_data_df.pkl: module 'load_data' has no attribute 'get_nan_removed_gaze_data_df'
